# Generated by Django 4.2.6 on 2023-10-17 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_transactionhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_Date', models.DateField()),
                ('quantity', models.BigIntegerField()),
                ('purchase_Value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='companyName',
            new_name='company_Name',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='marketcap',
            new_name='market_cap',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='symbol',
            new_name='stock_Name',
        ),
        migrations.DeleteModel(
            name='TransactionHistory',
        ),
        migrations.AddField(
            model_name='transaction',
            name='stock_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.companyprofile'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
